### ISSUE TITLE
There are ads though...

### ISSUE THREAD

**Issue by ghost** [gallant4473/my-anime#1]
Since you download anime directly from Gogoanime, the ads that are specifically placed on top of the video stream also get hotlinked to your web app.

**Comment by animemandir** [comment]
Wel

> Since you download anime directly from Gogoanime, the ads that are specifically placed on top of the video stream also get hotlinked to your web app.

I dont see any ads here tho...
![image](https://user-images.githubusercontent.com/78192713/131975681-2b32c63b-890b-472c-b046-755ffabb96eb.png)
